# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto update

on:
  schedule:
    - cron: "0 22 * * 1"  # scheduled at 06:00 (UTC+8) every monday
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: merge
      run: |
        rm ./Complete.conf
        rm ./sr_top500_banlist_ad.conf
        wget https://cdn.jsdelivr.net/gh/lhie1/Rules/Shadowrocket/Complete.conf
        wget https://h2y.github.io/Shadowrocket-ADBlock-Rules/sr_top500_banlist_ad.conf
        python ./merge-h2y.py
        python ./merge-lhie1.py
    - name: commit
      run: |
        git config --global user.email actions@github.com
        git config --global user.name 'GitHub Actions'
        git add .
        git commit -m "update" -a
        git push
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
